name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Download
        run: node main.js
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.9.1
        with:
          push_options: '--force'